export const DUCK_ACTION_PREFIX = `react-spa-private/ducks/`;

export const AJAX_PREFIX = "FETCHING";
export const AJAX_POSTFIX_INIT = "INIT";
export const AJAX_POSTFIX_SUCCESS = "SUCCESS";
export const AJAX_POSTFIX_FAILURE = "FAILURE";
export const AJAX_POSTFIX_DOWNLOAD_PROGRESS = "DOWNLOAD_PROGRESS";
export const AJAX_POSTFIX_UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const AJAX_POSTFIX_CANCEL = "CANCEL";

export const AJAX_POSTFIX_SET_CANCEL_FN = "SET_CANCEL_FN";
